server:
  port: 9001

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

  rabbitmq:
    username: guest
    password: guest
    port: 5672
    addresses: 192.168.15.100
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
        #开启ack
      direct:
        acknowledge-mode: auto
      #支持消息的确认与返回
    template:
      mandatory: true
    publisher-confirm-type: simple

management:
  endpoints:
    web:
      exposure:
        include:  '*'

service-url.nacos-payment-provider: "http://nacos-payment-provider"